### PR TITLE
Support keeping segments together

### PR DESCRIPTION
**Pull request by bertfrees**
This solve the problem I described in https://github.com/brailleapps/dotify.api/issues/13 without changing the BrailleTranslator contract. The problem is that currently it may happen that a line is broken exactly in between two segments while it isn't always allowed.

Depends on https://github.com/brailleapps/dotify.formatter.impl/pull/44.

### CODE REVIEW

**Comment by joeha480** [comment]
@bertfrees I rebased this and pushed to https://github.com/brailleapps/dotify.formatter.impl/tree/sbsdev-keep-segments-together

There's some issue with leaders (at least).

**Comment by bertfrees** [comment]
Does this fix it? https://github.com/sbsdev/dotify.formatter.impl/compare/master...sbsdev-keep-segments-together

**Comment by joeha480** [comment]
@bertfrees Does it pass the regression tests? If so, could you rebase and fixup the PR?

**Comment by joeha480** [comment]
@bertfrees It's still failing. You should run the regression tests yourself, otherwise this could take a long time to fix.

**Comment by bertfrees** [comment]
Rebased. Will try to run regression tests now.

**Comment by bertfrees** [comment]
Rebased this branch onto latest master.

**Comment by joeha480** [comment]
@bertfrees Regression tests are failing.

**Comment by bertfrees** [comment]
I'm getting this error if I try to run the regression tests:

```
* Where:
Build file '/home/frees/src/dotify-regression-tests/build.gradle' line: 152

* What went wrong:
Execution failed for task ':runRegression'.
> Expected directory 'build/unzip/dotify-cli/lib' to contain exactly one file, however, it contains more than one file.
```

I removed the build/unzip directory beforehand. After running the command it contains these files:
```
ls build/unzip/dotify-cli/lib
braille-utils.api-3.0.0.jar              dotify.common-4.3.1.jar                   dotify.translator.impl-4.0.0.jar
braille-utils.basic-cli-1.0.0.jar        dotify.formatter.impl-2.7.1-SNAPSHOT.jar  jing-20120724.0.0.jar
braille-utils.impl-3.0.0-beta.jar        dotify.formatter.impl-4.5.0-SNAPSHOT.jar  saxon-he-9.5.1.5.jar
braille-utils.impl-6.0.0.jar             dotify.hyphenator.impl-2.0.1.jar          stax2-api-3.1.4.jar
braille-utils.pef-tools-2.0.0-alpha.jar  dotify.hyphenator.impl-4.0.0.jar          stax2-api-4.1.jar
braille-utils.pef-tools-5.0.0.jar        dotify.task-api-2.3.0.jar                 streamline-api-1.3.0.jar
braille-utils.ui-2.0.0-beta1.jar         dotify.task.impl-2.11.0.jar               streamline-cli-1.0.0.jar
dotify.api-2.10.1-SNAPSHOT.jar           dotify.task.impl-4.6.0.jar                streamline-engine-1.2.0.jar
dotify.api-4.5.0.jar                     dotify.task-runner-1.1.0.jar              texhyphj-1.2.jar
dotify-cli-3.0.0-SNAPSHOT.jar            dotify.text.impl-2.0.0.jar                woodstox-core-5.0.2.jar
dotify-cli-3.1.1-SNAPSHOT.jar            dotify.text.impl-4.0.0.jar                woodstox-core-5.1.0.jar
dotify.common-2.1.0.jar                  dotify.translator.impl-2.3.0.jar          xml-apis-1.4.01.jar
```

The updateBaseline task has already been done before.

**Comment by joeha480** [comment]
That's because you have multiple versions of the dotify-zip in build-resources/dist. If you run with `copy_build=true`, then you should also check that you don't have multiple versions in `$dotifyPath/build/distributions`.

**Comment by bertfrees** [comment]
Thanks

**Comment by joeha480** [comment]
I am closing this as it causes regression and no fix for this has been provided.

**Pull request closed without merging**
