### PR TITLE
Change splitter API, make more use of immutability, and reimplement "text flow in header/footer" feature

### PR DESCRIPTION
**Pull request by bertfrees**
Depends on https://github.com/brailleapps/dotify.common/pull/6

### CODE REVIEW

**Comment by joeha480** [comment]
I am getting an error already in the dotify-cli tests.

**Comment by joeha480** [comment]
I have merged fa3550f and 6e6cb23 (which are unaffected by the error introduced in the dotify-cli tests).

**Comment by bertfrees** [comment]
@joeha480 I pushed some more stuff which should hopefully make it possible for you to continue with the integration tests.

**Comment by joeha480** [comment]
I am closing this because I don’t think it is compatible with master anymore.

**Pull request closed without merging**
