### PR TITLE
Implement new marker-reference scope "spread-content"

### PR DESCRIPTION
**Pull request by bertfrees**
See issues https://github.com/brailleapps/dotify/issues/144 and https://github.com/brailleapps/dotify/issues/150

Depends on https://github.com/brailleapps/dotify.api/pull/10

### CODE REVIEW

**Comment by joeha480** [comment]
Merged in cf591555a3d46e7838bc7d2282946cee45bd22fe. Thanks!

**Comment by joeha480** [comment]
By the way, a test for this would have been nice.

**Comment by bertfrees** [comment]
I'll do it tomorrow.

**Comment by joeha480** [comment]
Merged in
f55a17dafb28a7eea50b0b420035c978295d42da
and
c04219ec135f8056bf3cf752c2208f3fc92409e9

**Pull request closed without merging**
