### PR TITLE
Various fixes to volume breaking

### PR DESCRIPTION
**Pull request by bertfrees**
NLB implemented advanced volume breaking in their CSS style sheet but was having some issues running the style sheet on real books. I helped them fix it. Jostein has made several unit tests in https://github.com/nlbdev/pipeline/blob/nlb/modules/nlb/book-to-pef/src/test/xprocspec/test_dtbook-to-pef_volume-breaking.xprocspec. I suppose we could convert them into Dotify tests.

### CODE REVIEW

**Comment by bertfrees** [comment]
And we should probably run the MTM regression test suite.

**Comment by joeha480** [comment]
We decided to wait until the row-by-row thing is finished.

**Comment by bertfrees** [comment]
@joeha480 I updated and rebased this PR.

**Comment by joeha480** [comment]
So, I have had a first look and here are some results (excluding commits 8bbd535 and b5bd789, which we should discuss separately). For the remaining commits, all but one file passes regression and in that case the number of volumes dropped from 18 to 17, so that's good. However, because of this, I think I should make a new release of dotify-cli as soon as possible so that the regression suite can be updated again. Right now, I am doing a benchmark of the modified suite and assuming that goes well, I can merge these commits to master.

Aside from the above mentioned commits, we could also discuss 58d9008, because at the moment I cannot tell if it's correct or not (I don't mean your change, but the cost function in general seems slightly off to me).

**Comment by bertfrees** [comment]
Great!

Should we discuss the commits you mentioned Thursday? Or here on Github?

**Comment by joeha480** [comment]
I meant Thursday... :)

On second thought, I should probably wait with the new release until we have sorted the remaining commits. Therefore, I will not merge these to master until that time.

By the way, the benchmark was inconclusive. I cannot see any performance improvement, which is odd since fewer iterations should have had that effect. It's not the worst time I have seen, but not the best either (since the refactoring I made).

**Pull request closed without merging**
