### PR TITLE
Allow text flow

### PR DESCRIPTION
**Pull request by bertfrees**
See braillespecs/obfl#60 and https://github.com/brailleapps/dotify.formatter.impl/issues/13

Depends on https://github.com/brailleapps/dotify.api/pull/11

### CODE REVIEW

**Comment by bertfrees** [comment]
Please wait with merging this. Commit 6a193b1eb6a29f393d17a4248972f0c1e99942dd has broken your regression tests. It appears to influence the evaluation of marker-reference somehow.

**Comment by bertfrees** [comment]
There are two problems:

1. There was a small bug that was causing the new "data flow" to be "activated" in the regression tests, even though I intended the flow to be exactly the same as before when there are no headers or footers that allow text to flow in them. I have fixed this.

2. The second problem is more serious. When there are headers or footers that allow text to flow in them, the computation of header and footer fields is done sooner, namely at a point in time when not all pages have been added to the page sequence yet and the volume scopes haven't been set on the page structs. In the case of marker-reference fields this is problematic because in order to resolve them, info about preceding and following pages and volume scopes is needed.

@joeha480 What should we do? Fix 1, then merge, then try to come up with a solution for 2?

**Comment by bertfrees** [comment]
Added some more commits. Regression tests complete.txt and all-dls.txt now pass. I would say it is ready to be merged now.

Problem 2 isn't really a problem for SBS because they don't use print page numbers in combination with text flow into footer. So we could just make the pagination fail whenever this combination happens (currently it just returns a wrong result).

But here is an idea for how to fix it: when a PageImpl is created we can add it to a temporary PageSequence. That PageSequence will not be complete when we want to compute the header/footer fields, but for most cases it doesn't have to be complete. Usually it will be enough to be able to look back, or one page ahead. Note that looking ahead can be tricky, even if it is only one page, because the markers of the next page depend on where the page ends, which in turn could depend on the markers of the page after it. So it would not be enough to buffer one page. Luckily, in most cases where we need to look ahead one page, we only need it every other page. In the cases where we need volume information to compute the marker-reference, I also don't see an obvious solution, we really need volume breaking and page breaking to be done at the same time for that. In all the cases we don't support we just throw an error. Or we could reserve some space for the marker-reference fields and then only throw an error if the space gets exceeded.

**Comment by joeha480** [comment]
Could you rebase this? I think there's a conflict with some of the changes you made in another PR.

**Comment by bertfrees** [comment]
Done

**Comment by joeha480** [comment]
I have merged this now. Thanks!

**Pull request closed without merging**
