### PR TITLE
Allow right aligned leaders to extend into the box' margin

### PR DESCRIPTION
**Pull request by bertfrees**
I have done this change to implement a requirement that both SBS and NLB had:

- https://github.com/sbsdev/pipeline-mod-sbs/issues/51
- https://github.com/nlbdev/pipeline/issues/169

See also the related braille-css issue: https://github.com/braillespecs/braille-css/issues/21#issuecomment-385033731

### CODE REVIEW

**Comment by bertfrees** [comment]
@joeha480 Have you seen this?

**Comment by joeha480** [comment]
Yes, I have. We can talk about it in the next meeting.

**Comment by kalaspuffar** [comment]
This is should handled in OBFL and we will create a new PR for this.

**Comment by bertfrees** [comment]
I've created the OBFL issue: https://github.com/braillespecs/obfl/issues/78

**Comment by bertfrees** [comment]
Created new Dotify issue: https://github.com/brailleapps/dotify.formatter.impl/issues/113

**Pull request closed without merging**
