### PR TITLE
Support grouping of collection items according to volume

### PR DESCRIPTION
**Pull request by bertfrees**
as explained in issue https://github.com/braillespecs/obfl/issues/58

Depends on https://github.com/brailleapps/dotify.api/pull/9.

### CODE REVIEW

**Comment by joeha480** [comment]
Merged in 998accab973c3461dc08c2d27f657f60501fca83. Thanks!

**Comment by joeha480** [comment]
By the way, a test for this would have been nice.

**Comment by bertfrees** [comment]
I'll do it tomorrow.

**Comment by joeha480** [comment]
Merged in 88e287479c1305ee3d3e474b99b93dc3b92202da. Thanks!

**Pull request closed without merging**
